// ============================================================
// ISutra: Phase D — Benchmark Evaluation Cases
// Ground Truth Dataset for End-to-End Recommendations Evaluation
// ============================================================

export type EvaluationOutcome = 'match' | 'blocked_readiness' | 'contradiction' | 'no_match';

export interface EvaluationCase {
  id: string;
  domain: 'Lighting' | 'Cables' | 'Civil' | 'Safety' | 'Ambiguous' | 'Contradiction';
  input: string;
  expected_standard_numbers: string[];
  expected_domain: string;
  expected_product_form?: string;
  should_be_ready_for_matching: boolean;
  expected_outcome: EvaluationOutcome;
  notes: string;
  phase?: 'D' | 'E';
  competing_broad_standard?: string;
}

export const PHASE_D_EVALUATION_CASES: EvaluationCase[] = [
  // ------------------------------------------------------------
  // DOMAIN 1: Lighting & Luminaires (7 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-light-01',
    domain: 'Lighting',
    input: 'Procure 100W LED street lighting luminaires for municipal highway road lighting with outdoor weather-resistant housing.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 3):2026', 'IS 16107 (Part 2/Sec 2):2017'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'street_road_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Classic street lighting tender specification. Must retrieve dedicated road & street luminaire standards at top ranks.',
  },
  {
    id: 'eval-light-02',
    domain: 'Lighting',
    input: 'Supply self-contained emergency lighting luminaires for commercial building exit corridors with autonomous battery backup.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 8):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'emergency_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Dedicated emergency lighting standard must rank #1 over generic luminaires.',
  },
  {
    id: 'eval-light-03',
    domain: 'Lighting',
    input: 'Procure outdoor floodlight luminaires with high illumination output for sports stadium and industrial yard perimeter.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 5):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'floodlight',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Floodlight specific requirements must favor Section 5 floodlight standard.',
  },
  {
    id: 'eval-light-04',
    domain: 'Lighting',
    input: 'Supply 9W self-ballasted LED lamps for general lighting services with standard B22 cap for domestic and office use.',
    expected_standard_numbers: ['IS 16102 (Part 1):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'self_ballasted_lamp',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Lamp / bulb product form must be distinguished from complete luminaire fittings.',
  },
  {
    id: 'eval-light-05',
    domain: 'Lighting',
    input: 'Procure LED modules for general lighting applications to be integrated into commercial indoor luminaire assemblies.',
    expected_standard_numbers: ['IS 16103 (Part 1):2025', 'IS 16103 (Part 2):2025'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'led_module',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Modular light engine component must match IS 16103 series.',
  },
  {
    id: 'eval-light-06',
    domain: 'Lighting',
    input: 'Supply portable handlamps for heavy vehicle maintenance workshop inspection pits with insulated protective casing.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 6):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'general_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Handlamps particular requirements standard under IS 10322 Section 6.',
  },
  {
    id: 'eval-light-07',
    domain: 'Lighting',
    input: 'Supply fixed general purpose indoor luminaires for municipal office room ceiling lighting installations.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 1):2026', 'IS 10322 (Part 1):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'general_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Fixed general purpose luminaires standard under IS 10322 Section 1.',
  },

  // ------------------------------------------------------------
  // DOMAIN 2: Electrical Cables & Wires (6 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-cable-01',
    domain: 'Cables',
    input: 'Supply PVC insulated heavy duty electric cables for working voltages up to and including 1100V for industrial power feed.',
    expected_standard_numbers: ['IS 1554 (Part 1):1988'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Direct match for heavy duty low voltage PVC power cables.',
  },
  {
    id: 'eval-cable-02',
    domain: 'Cables',
    input: 'Procure XLPE insulated thermoplastic sheathed power cables for working voltages from 3.3 kV up to 33 kV for substation grid.',
    expected_standard_numbers: ['IS 7098 (Part 2):2011'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Medium voltage XLPE power distribution cable specification.',
  },
  {
    id: 'eval-cable-03',
    domain: 'Cables',
    input: 'Supply aerial bunched cables (ABC) for working voltages up to 1100V for overhead rural power distribution lines.',
    expected_standard_numbers: ['IS 14255:1995'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Aerial bunched conductor system for overhead electrification.',
  },
  {
    id: 'eval-cable-04',
    domain: 'Cables',
    input: 'Procure halogen free flame retardant (HFFR) cables for working voltages up to 1100V in underground metro rail stations.',
    expected_standard_numbers: ['IS 17048:2018'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Low smoke halogen free flame retardant power cable.',
  },
  {
    id: 'eval-cable-05',
    domain: 'Cables',
    input: 'Supply copper conductor PVC insulated unsheathed and sheathed flexible cords for internal electrical wiring rated up to 450/750V.',
    expected_standard_numbers: ['IS 694:2010'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Standard building wiring and flexible cords specification.',
  },
  {
    id: 'eval-cable-06',
    domain: 'Cables',
    input: 'Procure elastomer insulated flexible cables for working voltages up to 1100V for heavy duty mining and industrial machinery.',
    expected_standard_numbers: ['IS 9968 (Part 1):2025'],
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'electrical_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Heavy duty elastomer rubber insulated cable standard.',
  },

  // ------------------------------------------------------------
  // DOMAIN 3: Civil & Construction (9 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-civil-01',
    domain: 'Civil',
    input: 'Structural plain and reinforced concrete works for construction of multi-storey commercial building foundation and columns.',
    expected_standard_numbers: ['IS 456:2000'],
    expected_domain: 'Construction → Concrete',
    expected_product_form: 'structural_concrete',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Flagship Indian standard for plain and reinforced concrete code of practice.',
  },
  {
    id: 'eval-civil-02',
    domain: 'Civil',
    input: 'Supply high strength deformed TMT steel bars Fe 500D for concrete reinforcement in bridge pier construction.',
    expected_standard_numbers: ['IS 1786:2008'],
    expected_domain: 'Construction → Reinforcement Steel',
    expected_product_form: 'reinforcing_steel',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'High strength deformed steel bars and wires for concrete reinforcement.',
  },
  {
    id: 'eval-civil-03',
    domain: 'Civil',
    input: 'Procure coarse and fine aggregate from natural sources for concrete construction batching plant.',
    expected_standard_numbers: ['IS 383:2016'],
    expected_domain: 'Construction → Aggregates',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Coarse and fine aggregates specification for concrete.',
  },
  {
    id: 'eval-civil-04',
    domain: 'Civil',
    input: 'Supply hot rolled medium and high tensile structural steel plates and sections for industrial warehouse fabrication.',
    expected_standard_numbers: ['IS 2062 (Part 1):2025'],
    expected_domain: 'Construction → Structural Steel',
    expected_product_form: 'structural_steel',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Structural steel hot rolled product standard.',
  },
  {
    id: 'eval-civil-05',
    domain: 'Civil',
    input: 'Supply reinforced precast concrete pipes class NP3 for municipal highway culvert and drainage pipeline.',
    expected_standard_numbers: ['IS 458:2021'],
    expected_domain: 'Construction → Concrete Products',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Precast concrete pipes with and without reinforcement.',
  },
  {
    id: 'eval-civil-06',
    domain: 'Civil',
    input: 'Procure precast concrete masonry blocks solid and hollow units for non-load bearing building perimeter walls.',
    expected_standard_numbers: ['IS 2185 (Part 1):2005'],
    expected_domain: 'Construction → Masonry',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Concrete masonry units hollow and solid blocks.',
  },
  {
    id: 'eval-civil-07',
    domain: 'Civil',
    input: 'Supply common burnt clay building bricks of class 7.5 for general masonry wall construction.',
    expected_standard_numbers: ['IS 1077:2025'],
    expected_domain: 'Construction → Bricks',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Common burnt clay building bricks specification.',
  },
  {
    id: 'eval-civil-08',
    domain: 'Civil',
    input: 'Concrete mix proportioning design guidelines for design of M25 grade reinforced cement concrete.',
    expected_standard_numbers: ['IS 10262:2019'],
    expected_domain: 'Construction → Concrete',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Concrete mix proportioning guidelines.',
  },
  {
    id: 'eval-civil-09',
    domain: 'Civil',
    input: 'Design and construction of liquid retaining reinforced concrete structures for municipal overhead water tank reservoir.',
    expected_standard_numbers: ['IS 3370 (Part 1):2021'],
    expected_domain: 'Construction → Water Retaining Structures',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Code of practice for concrete structures retaining aqueous liquids.',
  },

  // ------------------------------------------------------------
  // DOMAIN 4: Safety & Personal Protective Equipment (5 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-safety-01',
    domain: 'Safety',
    input: 'Supply industrial safety footwear with steel toe cap and slip resistant polyurethane sole for workshop technicians.',
    expected_standard_numbers: ['IS 15298 (Part 2):2024'],
    expected_domain: 'Safety → Personal Protective Equipment',
    expected_product_form: 'safety_footwear',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Personal protective equipment Part 2 safety footwear.',
  },
  {
    id: 'eval-safety-02',
    domain: 'Safety',
    input: 'Procure protective gloves against mechanical risks including abrasion and puncture for sheet metal factory workers.',
    expected_standard_numbers: ['IS 6994 (Part 6):2021', 'IS 6994 (Part 7):2021'],
    expected_domain: 'Safety → Personal Protective Equipment',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Mechanical risk hand protection gloves.',
  },
  {
    id: 'eval-safety-03',
    domain: 'Safety',
    input: 'Procure firefighter protective clothing for structural firefighting operations with flame resistant outer shell.',
    expected_standard_numbers: ['IS 16890:2024'],
    expected_domain: 'Safety → Firefighter PPE',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Textiles protective clothing for firefighters.',
  },
  {
    id: 'eval-safety-04',
    domain: 'Safety',
    input: 'Supply protective clothing designed to protect industrial workers against extreme heat and radiant flame hazards in foundry.',
    expected_standard_numbers: ['IS 15748:2022'],
    expected_domain: 'Safety → Protective Clothing',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Heat and flame protective clothing specification.',
  },
  {
    id: 'eval-safety-05',
    domain: 'Safety',
    input: 'Supply respiratory protective devices powered filtering respirators incorporating a protective hood for chemical powder handling.',
    expected_standard_numbers: ['IS 19089:2025'],
    expected_domain: 'Safety → Respiratory Protection',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    notes: 'Powered filtering respiratory protective devices.',
  },

  // ------------------------------------------------------------
  // DOMAIN 5: Ambiguous / Insufficient Information (Phase A Blocking) (4 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-ambig-01',
    domain: 'Ambiguous',
    input: 'Supply electrical equipment for a building.',
    expected_standard_numbers: [],
    expected_domain: 'Ambiguous',
    should_be_ready_for_matching: false,
    expected_outcome: 'blocked_readiness',
    notes: 'Extremely vague requirement lacking specific product type and technical context. Phase A must block matching.',
  },
  {
    id: 'eval-ambig-02',
    domain: 'Ambiguous',
    input: 'Provide lighting equipment.',
    expected_standard_numbers: [],
    expected_domain: 'Ambiguous',
    should_be_ready_for_matching: false,
    expected_outcome: 'blocked_readiness',
    notes: 'Generic lighting query without product form or application. Must be blocked for clarification.',
  },
  {
    id: 'eval-ambig-03',
    domain: 'Ambiguous',
    input: 'Supply construction materials.',
    expected_standard_numbers: [],
    expected_domain: 'Ambiguous',
    should_be_ready_for_matching: false,
    expected_outcome: 'blocked_readiness',
    notes: 'Generic civil query without concrete, steel, brick, or cement specification. Must be blocked.',
  },
  {
    id: 'eval-ambig-04',
    domain: 'Ambiguous',
    input: 'Need good quality protective equipment.',
    expected_standard_numbers: [],
    expected_domain: 'Ambiguous',
    should_be_ready_for_matching: false,
    expected_outcome: 'blocked_readiness',
    notes: 'Generic PPE mention without identifying shoes, gloves, helmet, or respiratory gear. Must be blocked.',
  },

  // ------------------------------------------------------------
  // DOMAIN 6: Negative & Contradiction Cases (Phase B Contradiction Handling) (3 cases)
  // ------------------------------------------------------------
  {
    id: 'eval-contra-01',
    domain: 'Contradiction',
    input: 'Supply emergency lighting luminaires dedicated exclusively for outdoor municipal highway road lighting installations.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 3):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'emergency_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'contradiction',
    notes: 'Contradiction: Emergency lighting product form conflicting with municipal highway road lighting application. Must flag contradiction.',
  },
  {
    id: 'eval-contra-02',
    domain: 'Contradiction',
    input: 'Fixed general purpose indoor luminaires specified for outdoor weather-resistant highway road lighting use.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 1):2026'],
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'general_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'contradiction',
    notes: 'Contradiction: Indoor fixed luminaire specified for outdoor weather-resistant application.',
  },
  {
    id: 'eval-contra-03',
    domain: 'Contradiction',
    input: 'Supply high strength deformed TMT steel reinforcement bars specified with crosslinked polyethylene XLPE insulation and copper conductors for concrete slab foundations.',
    expected_standard_numbers: ['IS 1786:2008'],
    expected_domain: 'Civil & Construction',
    expected_product_form: 'reinforcing_steel',
    should_be_ready_for_matching: true,
    expected_outcome: 'contradiction',
    notes: 'Contradiction: Construction reinforcement described using cable terminology (XLPE insulation, copper conductor).',
  },
];

// ============================================================
// Phase E: Specificity-Aware Ranking Evaluation Cases (12 cases)
// Dedicated benchmark cohort to evaluate specific vs broad standards,
// product vs general material standards, component vs system standards,
// and contradiction dominance.
// ============================================================
export const PHASE_E_EVALUATION_CASES: EvaluationCase[] = [
  // Case E-01: Cables — Specific XLPE vs Broad PVC (IS 7098 vs IS 1554)
  {
    id: 'eval-e-01',
    domain: 'Cables',
    input: 'Procure 11kV crosslinked polyethylene (XLPE) insulated power cables for underground electrical power distribution network.',
    expected_standard_numbers: ['IS 7098 (Part 2):2011'],
    competing_broad_standard: 'IS 1554 (Part 1):1988',
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'xlpe_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'XLPE high voltage power cable vs broad PVC heavy duty cable (IS 7098 vs IS 1554). Specific standard must rank #1.',
  },
  // Case E-02: Cables — Specific Flexible Cord vs Broad Heavy Duty Cable (IS 694 vs IS 1554)
  {
    id: 'eval-e-02',
    domain: 'Cables',
    input: 'Supply multi-core copper conductor flexible PVC cords for household electrical appliances and domestic wiring connections.',
    expected_standard_numbers: ['IS 694:2010'],
    competing_broad_standard: 'IS 1554 (Part 1):1988',
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'pvc_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Flexible PVC cord vs heavy duty industrial power cable (IS 694 vs IS 1554). Appliance cord standard must rank #1.',
  },
  // Case E-03: Civil — Specific Precast Concrete Pipes vs General Mix Design (IS 458 vs IS 10262)
  {
    id: 'eval-e-03',
    domain: 'Civil',
    input: 'Supply precast reinforced concrete pipes class NP3 with spigot and socket joints for municipal stormwater drainage culverts.',
    expected_standard_numbers: ['IS 458:2021'],
    competing_broad_standard: 'IS 10262:2019',
    expected_domain: 'Civil & Construction',
    expected_product_form: 'concrete_pipe',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Precast concrete pipes vs general concrete mix proportioning (IS 458 vs IS 10262). Dedicated pipe standard must rank #1.',
  },
  // Case E-04: Civil — Specific Concrete Masonry Blocks vs General Mix Design (IS 2185 vs IS 10262)
  {
    id: 'eval-e-04',
    domain: 'Civil',
    input: 'Procure solid and hollow precast concrete masonry blocks for non-load bearing and exterior masonry wall construction.',
    expected_standard_numbers: ['IS 2185 (Part 1):2005'],
    competing_broad_standard: 'IS 10262:2019',
    expected_domain: 'Civil & Construction',
    expected_product_form: 'concrete_block',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Concrete masonry blocks vs general concrete mix design (IS 2185 vs IS 10262). Finished masonry block standard must rank #1.',
  },
  // Case E-05: Civil — Specific Liquid Retaining Structure vs General Mix Design (IS 3370 vs IS 10262)
  {
    id: 'eval-e-05',
    domain: 'Civil',
    input: 'Design and construction of liquid retaining reinforced concrete reservoirs and water storage tanks for municipal supply.',
    expected_standard_numbers: ['IS 3370 (Part 1):2021'],
    competing_broad_standard: 'IS 10262:2019',
    expected_domain: 'Civil & Construction',
    expected_product_form: 'water_tank_structure',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Liquid-retaining aqueous structures vs general concrete mix code (IS 3370 vs IS 10262). Liquid-retaining standard must rank #1.',
  },
  // Case E-06: Safety — Specific Mechanical Protective Gloves vs Firefighter Gloves (IS 6994 vs IS 16874)
  {
    id: 'eval-e-06',
    domain: 'Safety',
    input: 'Procure industrial protective gloves offering certified mechanical hazard protection against abrasion, cut, tear, and puncture.',
    expected_standard_numbers: ['IS 6994 (Part 6):2021', 'IS 6994 (Part 7):2021'],
    competing_broad_standard: 'IS 16874:2018',
    expected_domain: 'Safety & PPE',
    expected_product_form: 'protective_gloves',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Protective gloves for mechanical risks vs firefighter gloves (IS 6994 vs IS 16874). Mechanical risk standard must rank #1.',
  },
  // Case E-07: Lighting — Specific Road/Street Luminaire vs Generic Luminaire (IS 10322 Part 5 Sec 3 vs Part 1)
  {
    id: 'eval-e-07',
    domain: 'Lighting',
    input: 'Procure outdoor street lighting luminaires with optical distribution for municipal highways and public road lighting.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 3):2026'],
    competing_broad_standard: 'IS 10322 (Part 1):2026',
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'street_road_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Specific street/road luminaire standard vs general luminaire requirements (IS 10322 Part 5 Sec 3 vs Part 1). Specific standard must rank #1.',
  },
  // Case E-08: Lighting — Component Standard vs Complete Luminaire System (IS 16103 vs IS 10322)
  {
    id: 'eval-e-08',
    domain: 'Lighting',
    input: 'Supply LED modules for general lighting applications to be built into customized indoor commercial architectural troffers.',
    expected_standard_numbers: ['IS 16103 (Part 1):2025'],
    competing_broad_standard: 'IS 10322 (Part 5/Sec 1):2026',
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'led_module',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'LED module component standard vs complete fixed luminaire fixture. Component standard must rank #1.',
  },
  // Case E-09: Safety — Application Specific Clothing vs Generic Safety Gear (IS 15748 vs Generic)
  {
    id: 'eval-e-09',
    domain: 'Safety',
    input: 'Procure certified protective clothing for industrial workers exposed to heat, radiant thermal flux, and flame hazards.',
    expected_standard_numbers: ['IS 15748:2022'],
    competing_broad_standard: 'IS 15298 (Part 2):2024',
    expected_domain: 'Safety & PPE',
    expected_product_form: 'heat_flame_clothing',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Heat & flame protective clothing vs safety footwear in the same PPE domain. Specific clothing standard must rank #1.',
  },
  // Case E-10: Cables — Specialized Aerial Bunched vs Underground Cable (IS 14255 vs IS 1554)
  {
    id: 'eval-e-10',
    domain: 'Cables',
    input: 'Supply aerial bunched cables (ABC) with crosslinked insulated aluminum conductors for rural overhead electrification distribution.',
    expected_standard_numbers: ['IS 14255:1995'],
    competing_broad_standard: 'IS 1554 (Part 1):1988',
    expected_domain: 'Electrical → Cables & Wires',
    expected_product_form: 'aerial_bunched_cable',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Aerial bunched cable vs standard underground PVC cable. Specialized ABC standard must rank #1.',
  },
  // Case E-11: Contradiction Dominance Test — Contradicted Standard Never Rescued
  {
    id: 'eval-e-11',
    domain: 'Contradiction',
    input: 'Procure self-contained emergency luminaires specifically intended for outdoor street lighting illumination on municipal expressways.',
    expected_standard_numbers: ['IS 10322 (Part 5/Sec 3):2026'],
    competing_broad_standard: 'IS 10322 (Part 5/Sec 8):2026',
    expected_domain: 'Electrical → Lighting',
    expected_product_form: 'emergency_luminaire',
    should_be_ready_for_matching: true,
    expected_outcome: 'contradiction',
    phase: 'E',
    notes: 'Contradiction Dominance: Emergency lighting standard has contradiction with outdoor street illumination and must NOT rank #1 despite matching keywords.',
  },
  // Case E-12: Unchanged Control Baseline — Plain Concrete Mix Proportioning (IS 10262)
  {
    id: 'eval-e-12',
    domain: 'Civil',
    input: 'Provide concrete mix proportioning and design guidelines for M30 grade concrete in multi-storey commercial building construction.',
    expected_standard_numbers: ['IS 10262:2019'],
    expected_domain: 'Civil & Construction',
    should_be_ready_for_matching: true,
    expected_outcome: 'match',
    phase: 'E',
    notes: 'Unchanged Control Baseline: IS 10262 correctly ranks #1 when mix proportioning design is explicitly the requested scope.',
  },
];

// Combined benchmark dataset (All 46 cases)
export const EVALUATION_CASES: EvaluationCase[] = [
  ...PHASE_D_EVALUATION_CASES,
  ...PHASE_E_EVALUATION_CASES,
];
